SELECT
    `id`,
    `sku`,
    `product`,
    `pcode`,
    `mrp`,
    COALESCE(`price`, `mrp`) AS `price`,
    `wsp`,
    `gst`,
    `size`,
    `discount`,
    `disc_type`,
    `brand`,
    `colour`,
    `label`,
    `section`,
    `season`,
    `category`,
    `upc`,
    `hsn`,
    `unit`,
    `prchd_on`,
    `purch_id`,
    `bill_number`,
    `supid`,
    `supplier`,
    `ean`,
    COALESCE(`cost`, `purch_price`) AS `cost`,
    COALESCE(`purch_price`, `cost`) AS `purch_price`,
    `cost_gst`,
    `qty`,
    `sold`,
    `defect`,
    `returned`,
    `available`,
    `product` as `original_name`
FROM `viewstock` ORDER BY `id` ASC;